# Generated by Django 3.0.5 on 2020-05-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('star', models.IntegerField()),
                ('main', models.CharField(max_length=100)),
                ('middle', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=400, verbose_name='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsite.Attraction')),
            ],
        ),
    ]
