# Generated by Django 3.0.5 on 2020-06-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordTable',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='newsite.AttTable')),
                ('valuation', models.CharField(blank=True, max_length=45, null=True)),
                ('view', models.CharField(blank=True, max_length=45, null=True)),
                ('cost', models.CharField(blank=True, max_length=45, null=True)),
                ('total', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyword_table',
                'managed': False,
            },
        ),
    ]
